package probabilistic_program;

import java.util.ArrayList;
import java.util.Random;

import controllers.LW_Controller;
import controllers.SMC_Controller;
import controllers.SSMH_Controller;
import machine.Machine;
import utils.Tuple;


public class ProbabilisticProgram {
    


    public static Tuple<Object, Float> runLWProbabilisticProgram(String program, Random rng){

        Machine machine = Machine.initial_machine(program, rng);    //We create the one machine

        LW_Controller lwController = new LW_Controller(machine, rng);   //Specific controller, knows the machine and RNG (seed)


        return lwController.runInference(); 

    }


    public static ArrayList<Float> runSMCProbabilisticProgram(String program, ArrayList<Random> rngs, int particle_qtty){
        ArrayList<Machine> particles = new ArrayList<Machine>();
        for(Random rng : rngs){
            
            //instantiate particle (machine) w/ specific seed and main environment
            Machine particle = Machine.initial_machine(program, rng);

            //add it to particle list
            particles.add(particle);
        }

        SMC_Controller smcController = new SMC_Controller(particles, rngs);  //We create specific controller (SMC) who will know particles (machines) w/ RNGs (seeds)

        //Run inference 
        return smcController.runInference();
        


    }


    public static ArrayList<Float> runSSMHProbabilisticProgram(String program, Random rng, int steps, int warmup){

        SSMH_Controller ssmhController = new SSMH_Controller(program, rng, steps, warmup);  //Specific controller (SSMH), no machines are instantiated as they will be generated by the inference algorithm


        return ssmhController.runInference();
    }


}
